// <auto-generated />

using System;

namespace BeatSaberMarkupLanguage
{
    namespace Attributes
    {
        internal class UIAction : Attribute { }
        internal class UIComponent : Attribute { }
        internal class UIObject : Attribute { }
        internal class UIParams : Attribute { }
        internal class UIValue : Attribute { }
    }
}
