// <auto-generated />

using System;

namespace HarmonyLib
{
    internal class HarmonyAttribute : Attribute { }
    internal class HarmonyCleanup : Attribute { }
    internal class HarmonyFinalizer : Attribute { }
    internal class HarmonyPatch : HarmonyAttribute { }
    internal class HarmonyPostfix : Attribute { }
    internal class HarmonyPrefix : Attribute { }
    internal class HarmonyPrepare : Attribute { }
    internal class HarmonyReversePatch : HarmonyAttribute { }
    internal class HarmonyTargetMethod : Attribute { }
    internal class HarmonyTargetMethods : Attribute { }
    internal class HarmonyTranspiler : Attribute { }
}
