//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatSaberMarkupLanguage.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeatSaberMarkupLanguage.Analyzers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t set UI fields to read only..
        /// </summary>
        internal static string AddReadonlyModifierUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("AddReadonlyModifierUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Field may be assigned through reflection..
        /// </summary>
        internal static string FieldNeverAssignedUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("FieldNeverAssignedUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t remove members marked with an attribute as they will be accessed through reflection..
        /// </summary>
        internal static string PrivateFieldAssignedButNeverUsedUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("PrivateFieldAssignedButNeverUsedUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harmony will call this method through reflection..
        /// </summary>
        internal static string PrivateMemberNeverUsedHarmonyPatchSuppressorJustification {
            get {
                return ResourceManager.GetString("PrivateMemberNeverUsedHarmonyPatchSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t remove members marked with an attribute as they will be accessed through reflection..
        /// </summary>
        internal static string PrivateMemberNeverUsedUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("PrivateMemberNeverUsedUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t remove members marked with an attribute as they will be accessed through reflection..
        /// </summary>
        internal static string RemoveUnreadPrivateMemberUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("RemoveUnreadPrivateMemberUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harmony will call this method through reflection..
        /// </summary>
        internal static string RemoveUnusedPrivateMemberHarmonyPatchSuppressorJustification {
            get {
                return ResourceManager.GetString("RemoveUnusedPrivateMemberHarmonyPatchSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t remove members marked with an attribute as they will be accessed through reflection..
        /// </summary>
        internal static string RemoveUnusedPrivateMemberUIAttributeSuppressorJustification {
            get {
                return ResourceManager.GetString("RemoveUnusedPrivateMemberUIAttributeSuppressorJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harmony requires special naming starting with underscores for parameters..
        /// </summary>
        internal static string StyleCopParameterNamingHarmonyPatchSuppressorJustification {
            get {
                return ResourceManager.GetString("StyleCopParameterNamingHarmonyPatchSuppressorJustification", resourceCulture);
            }
        }
    }
}
