name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - .github/workflows/set_up_env.ps1
    - BeatSaberMarkupLanguage/**
    - BeatSaberMarkupLanguage.sln
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\BeatSaberMarkupLanguage\manifest.json"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ secrets.BEAT_SABER_BINDINGS_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Download dependencies
      uses: nicoco007/download-beatmods-deps@main
      with:
        manifest: ${{ github.workspace }}\BeatSaberMarkupLanguage\manifest.json
        path: ${{ runner.temp }}\BeatSaberBindings

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GH Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build Debug
      run: dotnet build ${{ github.workspace }}\BeatSaberMarkupLanguage\BeatSaberMarkupLanguage.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberMarkupLanguage-${{ env.ZIP_VERSION }}-DEBUG
        path: ${{ github.workspace }}\BeatSaberMarkupLanguage\bin\Debug\net472\Final

    - name: Build Release
      run: dotnet build ${{ github.workspace }}\BeatSaberMarkupLanguage\BeatSaberMarkupLanguage.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberMarkupLanguage-${{ env.ZIP_VERSION }}-RELEASE
        path: ${{ github.workspace }}\BeatSaberMarkupLanguage\bin\Release\net472\Final
