name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - BeatSaberMarkupLanguage/**
    - BeatSaberMarkupLanguage.sln
  pull_request:

jobs:
  build:
    name: BeatSaberMarkupLanguage
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@v1
      with:
        access-token: ${{ secrets.BEAT_SABER_BINDINGS_TOKEN }}
        project-path: ${{ github.workspace }}\BeatSaberMarkupLanguage\BeatSaberMarkupLanguage.csproj

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GH Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build Debug
      id: build-debug
      run: dotnet build ${{ github.workspace }}\BeatSaberMarkupLanguage\BeatSaberMarkupLanguage.csproj -c Debug

    - name: Upload Debug
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-debug.outputs.artifact-name }}
        path: ${{ steps.build-debug.outputs.artifact-path }}

    - name: Build Release
      id: build-release
      run: dotnet build ${{ github.workspace }}\BeatSaberMarkupLanguage\BeatSaberMarkupLanguage.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
